spring:
  application:
    name: scs-retry-demo
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      topic:
        order-created: order-created
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.poc.scsretrydemo.OrderCreatedEvent
        spring.json.trusted.packages: com.poc.scsretrydemo
  cloud:
    stream:
      defaultBinder: kafka
      bindings:
        order-created-out-0:
          destination: order-created
          contentType: application/json
      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

server:
  port: ${SERVER_PORT:8081}
